### ISSUE TITLE
rework "normalizing" of composer versions

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-php-composer#102]
## backgroud
in php/composer the `v` prefix in versions is understood by the ecosystem.  it "heals" itself regarding a missing/existing `v`. 
in the lock file the actual version is used; the `v`  is added/removed to match the correct prefix of the actual version. ([example](https://github.com/CycloneDX/cyclonedx-php-composer/blob/master/demo/laravel-7.12.0/project/composer.lock))

i would prefer to keep the `v` if composer found that it is part of the actual version.

but unfortunately this would be a change of the [implementation since v1](https://github.com/CycloneDX/cyclonedx-php-composer/blob/1.x/src/BomGenerator.php#L133) that is actually kept until now(v3) since it seams to be there for a reason (, which drives me mad since the actual version sometimes  has a `v` for real). 

## proposal

dont handle a leading `v` in any special way. just leave everything as is.
additionally: make it optional(opt-in) to strip the `v` in front of a version. (only if there is an actual need for this, dont write this feature unless it is required)

## impact 
this would be a breaking change, since current implementation strips the `v` per default.
Proposed change would remove this behavior per default.

## acceptance criteria
- [ ] the `v` is not stripped, if composer tells that it exists.
- [ ] remove `--no-version-normalization` option and related capabilities
- [ ] remove the "normalizer" entirely

## work packages
tbd

**Comment by jkowalleck** [comment]
alternative: just dont touch the version string at all.
dont even have an option to strip the `v` at any point.

just like https://github.com/CycloneDX/cyclonedx-gomod/pull/60#issue-989407264

**Comment by jkowalleck** [comment]
is related to https://github.com/DependencyTrack/dependency-track/pull/1220

**Comment by jkowalleck** [comment]
is related to: https://github.com/DependencyTrack/dependency-track/issues/1243

**Comment by JorisVanEijden** [comment]
is related to https://github.com/OSSIndex/vulns/issues/231

**Comment by jkowalleck** [comment]
the behaviour wad changed and will be published via #250
