### ISSUE TITLE
add creation time to meta data

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-php-composer#112]
current implementation lacks the creation time in the meta data

for reproducible boms it's required to 
* either have a CLI flag/switch to not add the date
* or have a ENV var `CDX_REPRODUCIBLE` to not not add the date
* or have an option to determine the DateTIme

acceptance criteria
- [x] have creation time in meta data for XML
- [x] have creation time in meta data for JSON
- [x] time format is converted to zulu time, so there is no revelation of the timezoe the creating system is in 
- [x] have an option for reproducible-results

**Comment by jkowalleck** [comment]
fixed via #270
